- driver.go
- version/version.go
adds version package to drive plugin version, it will be parsed by our internal release tool as well for releases.hashicorp.com
> Add version

- CHANGELOG.md
- GNUmakefile
adds network pr to changelog, adds makefile with `changelogfmt`
> changelog entry and GNUmakefile

- .github/workflows/build.yml
- CHANGELOG.md
- GNUmakefile
- driver.go
> Do not explicitely pull images, rely on podman api instead

- CHANGELOG.md
- README.md
- config.go
- driver.go
- driver_test.go
> config: Support for sysctl configuration (#82)

- config.go
Small nit. I guess this was left from #78
> Cleanup unused dns in taskConfigSpec

- .github/machinesetup.sh
- Vagrantfile
> build: update Vagrant file to ubuntu focal.

- CHANGELOG.md
- README.md
- config.go
- driver.go
- driver_test.go
> config: map host devices into container

- CHANGELOG.md
- README.md
- config.go
- driver.go
- driver_test.go
This PR adds a privileged configuration option, similar to the docker driver.
> config: Privileged containers

- CHANGELOG.md
PR #152 was created before #169, but was not merged even though it has
pretty much the same code.
> changelog: add entry for #152

- README.md
- api/api.go
Fix podman default socket paths and update README so that it reflects the new default paths.
> Fix podman socket paths

- config.go
> chore: fix typo

- GNUmakefile
This just helps keep up with the nomad repo.
> deps: bump build tool versions

- README.md
This PR just updates the README documentation for the recover_stopped setting changes in https://github.com/hashicorp/nomad-driver-podman/pull/260
> Update README to reflect settings changes in PR #260

- registry/fileconfig.go
- registry/fileconfig_test.go
- registry/tests/auth.json
Fixes #269 
No CL, the auth stuff hasn't shipped yet.
> auth: skip registry auth file if config field is not set

- driver.go
Let Nomad Driver Podman work again in an environment without SystemD, for example on Alpine Linux with `cgroupfs` as alternative CGroup manager.
Fixes #274
> Pass nomad.slice as CGroup parent only on SystemD

- config.go
- driver.go
- driver_test.go
Closes https://github.com/hashicorp/nomad-driver-podman/issues/305
> Fixes shm_size in config not getting recognized.

- .github/workflows/build.yml
- .github/workflows/nightly-release.yml
internal ref: https://hashicorp.atlassian.net/browse/NET-10155
https://github.com/hashicorp/nomad-driver-podman/actions/runs/9939108031
> build: update actions and fix workflow_call trigger for nightly

- CHANGELOG.md
- GNUmakefile
> build: disable CGO for CRT release

- .release/nomad-driver-podman-artifacts.hcl
> Update artifact manifest license header

- driver.go
- driver_test.go
The podman driver was failing to decode the podman task config in task recovery scenarios because it was attempting to decode a private struct field that had previously been dropped after serialization. Adds tests to reduce likelihood of regression.
> fix podman config decoding and add task recovery tests

- driver.go
> fix tmpfs parser
