.gitignore

ignores `pkg/` which is added during build time by release tool

ignore release output directory

---

LICENSE

This repository is now owned and maintained by HashiCorp, as such we are migrating the license to MPL2.
Users who have used this repository prior to it being assigned to HashiCorp may still use it pursuant to APLv2. All Future changes will be pursuant to MPL2

change license to MPL2

---

CHANGELOG.md
driver.go

pr allows running connect job through docker network namespace
```hcl
job "countdash" {
datacenters = ["dc1"]
group "api" {
network {
mode = "bridge"
}
service {
name = "count-api"
port = "9001"
connect {
sidecar_service {}
}
}
task "web" {
driver = "podman"
config {
image = "hashicorpnomad/counter-api:v1"
}
}
}
group "dashboard" {
network {
mode = "bridge"
port "http" {
static = 9002
to     = 9002
}
}
service {
name = "count-dashboard"
port = "9002"
connect {
sidecar_service {
proxy {
upstreams {
destination_name = "count-api"
local_bind_port  = 8081
}
}
}
}
}
task "dashboard" {
driver = "podman"
env {
COUNTING_SERVICE_URL = "http://${NOMAD_UPSTREAM_ADDR_count_api}"
}
config {
image = "hashicorpnomad/counter-dashboard:v1"
}
}
}
}
```
podman.hcl
```
plugin_dir = "/opt/nomad/plugins" …
```

allow passed in network namespace

---

GNUmakefile
README.md
client.go
client_test.go
config.go
driver.go
driver_test.go
go.mod
go.sum
handle.go
iopodman/inspect.go
tools/go.mod
tools/go.sum
tools/tools.go

@weeezes I wanted to make a few changes to your PR to address the env and volumes  changes. Could you let me know if it works in your scenario?
For me the following works:
job file
```
job "example" {
datacenters = ["dc1"]
type        = "service"
group "cache" {
count = 1
restart {
attempts = 2
interval = "30m"
delay    = "15s"
mode     = "fail"
}
task "redis" {
driver = "podman"
config {
image = "redis"
port_map {
db = 6379
}
volumes = [
"alloc/:/mnt/alloc",
"local/:/mnt/local",
"secrets/:/mnt/secrets",
]
}
resources {
cpu    = 500 # 500 MHz
memory = 256 # 256MB
network {
port "db" {}
}
}
}
}
}
```
```
→ podman ps
CONTAINER ID  IMAGE                           COMMAND       CREATED        STATUS            PORTS                                                 NAMES
b3d720029540 …
```

Weeezes rootless + changes

---

CHANGELOG.md
README.md
config.go
driver.go
driver_test.go

Driver config can now specify a list of dns servers:
* **dns** - (Optional)  A list of dns servers. Replaces the default from podman binary and containers.conf.
```
config {
dns = [
"1.1.1.1"
]
}
```

config: Ability to configure dns server list

---

client.go
driver.go
go.mod
go.sum

Signed-off-by: Shishir Mahajan <smahajan@roblox.com>

Add support for SignalTask.

---

api/container_start.go
api/container_wait.go

Improve container startup state tracking. Some details can be found in #89 
It helps to overcome a race condition when running very short living containers in e.g. unit tests.
A better solution would be to continue on #80

Improve container_start to improve startup of short living containers

---

CHANGELOG.md
README.md
api/structs.go
driver.go

fix #92 parse rootless info correctly from podman 3.0.x struct
fix #93 use slirp4netns as default network mode if running rootless
Bump supported podman version in README to 3.0.x

Adopt some rootless code to podman 3.0.x

---

README.md
config.go
driver.go
driver_test.go

Issue #56 Plumb through Nomad network -> dns to podman

---

api/exec_create.go
api/exec_inspect.go
api/exec_resize.go
api/exec_start.go
api/structs.go
driver.go
go.mod

Alternative implementation to #85
It uses libpod api directly, following the minimal client strategy of our 0.2.0 release.
It's pretty complete and support both interactive use and scripted health checks. The only known issue is related to terminal resize events due to https://github.com/containers/podman/issues/7102 which should be fixed in the upcoming podman 3.0 release.

Exec support using libpod api

---

.github/workflows/build.yml
driver.go
driver_test.go

First of all, thank you very much for this plugin!
I was testing some basic configuration with nomad and this plugin and bumped into the following issue: 
With a clean podman installation, I tried to run the following task, which failed with `task=apache error="rpc error: code = Unknown desc = failed to start task, could not create container: unknown error, status code: 500: {"cause":"no such image","message":"unable to find 'docker.io/httpd:2' in local storage: no such image","response":500}"`
```
task "apache" {
driver = "podman"
config {
image = "docker.io/httpd:2"
ports = ["http"]
}
}
```
To my surprise, the image saved to storage was `httpd:latest` instead of `httpd:2`. I understand the reason is that podman interprets the missing tag as `latest` when asking `ImagePull` just for the …

Set tag when pulling image missing in local storage

---

README.md

In commit 2f33043 file was renamed from redis.nomad to redis_deprecated.nomad and a new file was created with the name redis_ports.nomad, but the README.md was not updated.

Put correct filename of the example job

---

.github/workflows/build.yml
api/api_test.go
api/image_pull.go
api/image_pull_test.go
api/structs.go

On the /images/pull endpoint, podman's StatusOK response does
not warranty that the image was actually pulled, just that
the request was well formatted and no InteralServerError happened.
If any error happens during the download, the error is written to
the output stream in the error field.
I bumped into this by doing a typo in an image name. The driver failed creating the container complaining about a missing image, which in theory had been pulled but was not in the container store. Manually requesting the API for the image yielded this result:
```
{"stream":"Trying to pull docker.io/library/nextcloud:alpine...\n"}
{"stream":"  manifest unknown: manifest unknown\n"}
{"error":"Error initializing source docker://nextcloud:alpine: Error reading manifest alpine in …
```

Fix errors missed while pulling images

---

.github/machinesetup.sh
.github/workflows/build.yml

[Podman team announced ](https://podman.io/blogs/2021/03/02/podman-support-for-older-distros.html) that they will no longer build packages for Ubuntu 18.04. 
This PR upgrades our github action runner to Ubuntu 20.04 and this brings us also from podman 3.0.1 to podman 3.1.x.

Update github action runner to ubuntu 20.04 and Podman 3.1.x

---

CHANGELOG.md
README.md
api/api.go
api/image_pull.go
api/image_pull_test.go
config.go
driver.go
driver_test.go

This addresses #71 
It adds a auth {username, password} task configuration option.

config: Image registry authentication #71

---

api/structs.go
driver.go
driver_test.go

README explains that we can use network_mode = container:$othercontainer to let one container joint the network of another, already running, container. This feature was not really implemented.
This PR adds now the missing implementation, fixes a podman json structure and includes a unit test.

Fix network_mode=container:$id network option

---

api/container_inspect.go
api/container_stop.go
driver.go
driver_test.go

Handle stopped and unknown/lost containers correctly while stopping a task.
The previous version let nomad run circles around lost containers. This happend when a group was reallocated to another node when a host was rebooted. After rebook, nomad tried to stop the already stopped container etc.  
I found that the docker driver has a similar if/else chain in StopTask, so i reassembled it here.

Improved StopTask in case that container was lost outside nomad

---

api/container_inspect.go
driver.go

Containers where not correctly deleted when recover_stopped=false is configured.
Also the driver is now less noisy if a container was lost whil nomad client was down.

Correctly recover containers after nomad restart when recover_stopped=false is configured.

---

driver.go
driver_test.go

We did not handle multiple mount options correctly. A comma separated string was not split up but instead handed over as a single option, thus configuring the container failed. 
A test is added to proof that it is working correctly now.

config: correctly handle multiple mount options per bind mount

---

README.md
driver.go
driver_test.go
examples/jobs/nats_group.nomad
examples/jobs/nats_pod.nomad
examples/jobs/nats_simple_pod.nomad
examples/jobs/templates/nats-server.conf.tpl

This PR add several new network related features.
First of all we can have now shared group network namespaces for e.g. consul connect. I aimed for rootful support and i am not sure if a rootless container can be joined to an existing network namespace somehow. 
A rootful container can, without any problems, join the nomad controlled network ns. We do not need a separate "pause" container like the docker driver implements it. This also means that this driver does not have to implement the CreateNetwork/DestroyNetwork hooks, so i it is more lightweight compared to the docker driver.
Additionally we have now two new network_mode values:
* network_mode = ns:/some/network/namespace  
* network_mode = task:name-of-other-task-in-same-group
The "task:" variant is very useful because a user can …

Add flexible network namespaces and shared group network namespace support for consul connect

---

CHANGELOG.md
driver.go
examples/nomad/client.hcl
handle.go

Use telemetry.collection_interval for each container monitor. Previously we polled for each container with a very fast, static, 1 second interval. This does not scale very well and we can see a considerable load on the podman service when running e.g. a job with 30 pause containers.

Respect telemetry.collection_interval to reduce cpu churn when running many containers 

---

api/image_inspect.go
driver.go
driver_test.go

This PR improves logging around long running pull or load operations. Further it emits a driver event before it start to pull or load an image to make a potential slow operation visible in the Nomad UI.

driver: emit a driver event when we pull or load an image

---

driver.go

Restores the previous default logging driver to json-file following
upstream podman change to journald.
Fixes #148

Set default logging driver to json-file

---

CHANGELOG.md
README.md
config.go
driver.go
driver_test.go

This increases the feature parity between docker and podman plugins. Nomad mounts are still successful inside the container.

config: Add readonly_rootfs config option like docker plugin

---

CHANGELOG.md
config.go
config_test.go
driver.go
driver_test.go

Nomad's docker driver allows having nomad set cpu resources as hard
limits rather than soft limits via the `cpu_hard_limits` driver config
option. This is useful to restrict how much CPU time a nomad job is
permitted to consume, even if the host is under utilised, or when
predicatibility is more important than speed.
Default behaviour is unchanged. When `cpu_hard_limit` is set to `true`
the podman container is started with the equivalent API options to the
podman cli `--cpu-quota` and `--cpu-period`.
Nomad currently provides a `PercentTicks` value which is used to convert
the cpu resource from the specification into a number of microseconds
of cputime the job is allowed to consume for each `period` interval of time.
Use of this value is discouraged ouside of the docker driver, however the …

Add cpu_hard_limit and cpu_cfs_period options

---

README.md

Seems like the README.md file had some commands with the `sh` syntax highlighting, but not all. Also, the HCL examples were missing highlighting. This PR adds them to make the rendered README look a bit nicer 🙂 
Link to rendered file: https://github.com/hashicorp/nomad-driver-podman/blob/4486e3bae6da45a330c8c7ed7f3fd10b74fd5ffb/README.md

Add syntax highlighting for `hcl` and `sh` code in README.md

---

driver_test.go

We have a architecture dependent image digest in one test. This PR adds a if/else for arm64/amd64. It enables a developer to run the full test suite on e.g. a M1 mac in a debian vm.

Fix image pull test for arm64 hosts

---

GNUmakefile
go.mod
go.sum
tools/go.mod
tools/go.sum

The go-discover mod had some broken deps (https://github.com/hashicorp/go-discover/issues/172) so this PR fixes that issue and updates hclogvet's branch to main. 
Without these changes, anyone building with a clean GOPATH will have a very broken dependency tree.

Fix broken go-discover dep tree. 

---

.github/CODEOWNERS

Locks down changes to release directories so that they require approval from release engineering, and so they have service account rights for pipeline runs and backport-assistant functionality.

Rdx 386 set codeowners

---

CHANGELOG.md
driver.go

Fixes https://github.com/hashicorp/nomad-driver-podman/issues/168. 
Tested running a job as both a CSI plugin and with a host volume:
<details><summary>jobspec</summary>
```hcl
job "hostpath" {
datacenters = ["dc1"]
group "plugins" {
volume "host_data" {
type      = "host"
read_only = false
source    = "shared_data"
}
task "plugin" {
driver = "podman"
config {
image = "quay.io/k8scsi/hostpathplugin:v1.2.0"
args = [
"--drivername=csi-hostpath",
"--v=5",
"--endpoint=${CSI_ENDPOINT}",
"--nodeid=node-${NOMAD_ALLOC_INDEX}",
]
cap_add = ["SYS_ADMIN"]
}
csi_plugin {
id        = "hostpath-plugin0"
type      = "monolith"
mount_dir = "/csi"
}
volume_mount {
volume      = "host_data"
destination = "/host_data"
read_only   = false
}
resources {
cpu    = 256
memory = 128
}
}
}
}
```
</details>
Working …

support host/CSI volumes and using podman tasks as CSI plugins

---

CHANGELOG.md
README.md
config.go
driver.go
driver_test.go

I guess the title is self-explanatory. 
The `sliceMergeUlimit` function is adapted from the nomad [docker driver](https://github.com/hashicorp/nomad/blob/main/drivers/docker/driver.go#L1723)

config: Add ulimit option like docker driver

---

CHANGELOG.md
README.md
config.go
config_test.go
driver.go
driver_test.go

Simple change to allow set http timeout via driver config.
Fix #100

http client timeout config

---

.github/workflows/build.yml

Add support for `arm` architecture. While we don't actively test it yet, adding it now will trigger this during the nightly builds for a while where the community can test it until the next releases.
Closes #178

build: add arm arch

---

CHANGELOG.md
driver.go
go.mod

podman does not establish a lock when it pulls an image. 
There is some movement towards a more efficient implementation via https://github.com/containers/podman/issues/1911
Other people workaround this problem by having a lock in another layer like e.g. https://github.com/cri-o/cri-o/pull/3409
This PR adds such a mechanism to nomad-driver-podman. It prevents to pull the same image on the same host concurrently. A good, manual, check is to run a job with e.g. 5x redis and to ensure that the image is locally not available. First allocation will pull the image, 4 others will wait until it is ready. Without this PR we would try to download it 5 times parallel, wasting time and bandwith.
There is no unit test because i could not figure out a good way to code it. Maybe i can get a …

Prevent concurrent image pulls of same imageRef

---

CHANGELOG.md
api/ping.go
driver.go
driver_test.go

All nomad drivers must implement a fingerprint mechanism. Back at the day i went with the system info api call and it worked well.  
But it turned out that this is a rather heavy invocation, going even down to the package manager level (dpkg, rpm) to gather informations. The driver builds a fingerprint each 30 seconds and thus it wastes quite some cpu cycles and has an impact on the overall machine load.
A simple `perf stat` on my machine shows the difference between the two podman cli equivalents:
```
Performance counter stats for 'podman info':
240.46 msec task-clock                #    0.721 CPUs utilized
1,481      context-switches          #    6.159 K/sec
141      cpu-migrations            #  586.383 /sec
18,851      page-faults               #   78.397 K/sec
0.333681791 seconds …
```

Use ping api instead of system info for fingerprinting

---

api/container_stats.go

Podman 4.1.1 changed the `stats` endpoint's HTTP status for stopped containers from 404 to 200.
Fixes #182
Closes #187

fix container stats endpoint response handling

---

CHANGELOG.md
README.md
config.go
driver.go
driver_test.go

Sometimes `--privileged` is too much and capabilities are not enough. This configuration option allow you to set a custom apparmor profile for a container to e.g. get elevated `/proc` permissions. It can also effectively disable apparmor by setting the value to `unconfined`.

config: Set custom apparmor profile or disable apparmor

---

CHANGELOG.md
README.md
api/structs.go
config.go
driver.go
driver_test.go

Solves #135 
Hi!
This PR adds support for the selinux_opts attribute, as per https://docs.podman.io/en/latest/_static/api.html#operation/ContainerCreateLibpod .
I've also updated the README file and the tests to support the new attribute.
Thank you!

Add support for container creation's selinux_opts attribute

---

driver_test.go

I merged #139 without checking the actual test result 🤦 
@jdoss did a great job [investigating how the SELinux project runs their CI](https://github.com/hashicorp/nomad-driver-podman/pull/139#issuecomment-1192929834), but running a Vagrant machine in our case seemed a bit much so I opted to just skipping these tests in CI for now.

ci: skip SELinux tests since they are not supported in GHA

---

CHANGELOG.md
README.md
config.go
driver.go
driver_test.go

Log collection in observability stacks (such as [via Vector](https://github.com/hashicorp/nomad-pack-community-registry/tree/main/packs/vector)) when using the `podman` driver isn't as literate as Docker. 
Add the option to add extra labels so promtail/vector/filebeat/whatever can get a view of what Nomad-related things running Podman containers may be doing.

Allow for an `extra_labels` stanza similar to the Docker driver

---

.github/workflows/tests.yml
CHANGELOG.md
driver.go
driver_test.go

Previously the value for `image_pull_timeout` was being capped by `client_http_timeout` because the image pull request used the same HTTP client as other requests.
Increasing `client_http_timeout` in order to be able to set a higher `image_pull_timeout` is not a good option since it requires updating all client's configuration. It also affects all other HTTP requests, which may not be desirable.
The change creates a separate client for slow operations that don't have a timeout configured. Operation timeout is controlled using a ContextWithTimeout().
Closes #207

driver: fix image_pull_timeout

---

README.md

#218 made it so  `image_pull_timeout` CAN be longer than `client_http_timeout`.  This PR is simply a fix of the overlooked README which affects the docs site.

Fix `image_pull_timeout` docs

---

GNUmakefile
ci/parallel.go
ci/special.go
config_test.go
driver_test.go

This PR
- adds a `ci.Parallel()` helper
- calls that instead of `testutils.IsCI()` from the `nomad` package
- runs most tests in parallel by default now
- replaces some duration calculation with direct values instead of calling `testutils.TestMultiplier()`
- add an explicit check for whether SELinux tests should run (`$CI_SELINUX`)

tests: detect CI without using nomad import

---

.github/CODEOWNERS
.github/workflows/build.yml
.github/workflows/nightly-release.yml

Many of the GitHub Actions from the build pipeline are written in a truly ancient version of NodeJS. Upgrade to more recent versions.
Fixes: #246

build: update deprecated GitHub Actions

---

GNUmakefile

This PR removes the `check` step from the `dev` target - when using
a `go.work` file the check step will prevent the dev target from being
succesfull, which makes things tedious when hacking on stuff.
The check target is run as part of CI; we should be fine there.

build: do not run check step during dev build

---

README.md
driver.go
driver_test.go

This PR makes it so that the Podman driver will now respect the task
config `resources.cores` value. When set, the task will be assigned the
specified number of CPU cores to be allowed to run on.
Note: unlike the docker/exec drivers, podman tasks will not be also allowed
to make use of the "shared" set of cpu cores (ones that have not yet been
reserved specifically for a task). Most likely that feature will be removed
in the near future (~Nomad 1.7) anyway.
Closes #160

driver: set cpuset when using cgroups v2

---

.github/dependabot.yaml

Currently we only get alerts pushed by GitHub security stuff, we should
run dependabot at least once a month just to pick up normal updates.

repo: setup dependabot to run monthly

---

config.go
config_test.go
driver.go
driver_test.go

This PR adds support for setting extra_hosts on in podman task configuration,
bringing the podman driver support up to par with the docker driver.
Closes #244

driver: add support for configuring extra_hosts in podman tasks

---

config.go
driver.go

The use of `recover_stopped` may cause the Nomad agent to hang on startup
after node reboot, as the plugin tries to start an exited podman task. 
Podman itself will hang forever in this state, and the http client on the
Nomad side is also unable to timeout in this case. The result is a permanently hung Nomad
agent, until someone force kills either Nomad or Podman.
Also emit a log warning that `recover_stopped` should not be used. We leave
it in place for compatibility.
Fixes #229

config: set recover_stopped to default to false

---

api/api.go
api/image_pull.go
api/image_pull_test.go
config.go
driver.go
driver_test.go
registry/authentication.go
registry/authentication_test.go
registry/credshelper.go
registry/credshelper_test.go
registry/fileconfig.go
registry/fileconfig_test.go
registry/tests/auth.json
registry/tests/docker-credential-fake.sh
registry/util.go
registry/util_test.go

This PR adds support for specifying an external credentials helper and/
or an external credentials file (e.g. "auth.json"). The plugin configuration
now has an `auth` block with fields `helper` and `config` (similar to
the docker driver). We also now have an `auth_soft_fail` option in Task
config for cases where someone has configured the `auth` block in plugin
config, but has a task that is using a public image with no credentials.
In that case setting `auth_soft_fail` is used to ignore the fact that
no credentials will be found for the given public image. (This is also
how the docker driver works, I didn't come up with this).
Unlike the docker driver, the podman driver still does not support
specifying a credentials helper _in_ the external "auth.json"
credentials file. If there is …

driver: support for credentials helper and auth config file

---

api/container_stats.go
api/structs.go

Fixes https://github.com/hashicorp/nomad-driver-podman/issues/277

Adjust `ContainerStats` for Podmod 4.6.0 responses

---

.github/machinesetup.sh

It seems the `podman` package for ubuntu now deactivates `podman` after install which means the socket activation does nothing. This explains why the `Run CI Tests` workflow has been completely broken recently. 
from a debug branch https://github.com/hashicorp/nomad-driver-podman/actions/runs/7183730982/job/19563150699#step:6:34
```
○ podman.service - Podman API Service
Loaded: loaded (/lib/systemd/system/podman.service; enabled; vendor preset: enabled)
Active: inactive (dead) since Tue 2023-12-12 15:35:06 UTC; 1min 20s ago
TriggeredBy: ○ podman.socket
Docs: man:podman-system-service(1)
Process: 2779 ExecStart=/usr/bin/podman $LOGGING system service (code=exited, status=0/SUCCESS)
Main PID: 2779 (code=exited, status=0/SUCCESS)
CPU: 86ms
```

build: ensure podman service is active

---

config.go
driver.go

so we can config dns for containers like:
```hcl
plugin "nomad-driver-podman" {
config {
dns_servers = ["192.168.8.100"]
}
}
```

feat: allow set global dns servers from client plugin config for contains

---

CHANGELOG.md
README.md
compat/nomad/client/stats/cpu.go
compat/nomad/client/stats/cpu_darwin_test.go
compat/nomad/client/stats/cpu_test.go
compat/nomad/client/stats/host.go
compat/nomad/client/stats/host_test.go
compat/nomad/helper/stats/cpu.go
compat/nomad/helper/stats/cpu_test.go
compat/nomad/helper/stats/runtime.go
config.go
driver.go
driver_test.go
lima.yaml

This is similar to https://github.com/hashicorp/nomad/pull/10156/files and allows for a configuration like:
```
plugin "nomad-driver-podman" {
config {
extra_labels = ["job_name", "job_id", "task_group_name", "task_name", "namespace", "node_name", "node_id"]
logging {
driver = "journald"
options = {
tag = "{{index .Config.Labels \"com.hashicorp.nomad.alloc_id\" }}"
}
}
}
}
```

Added a plugin logging configuration to specify defaults.

---

api/structs.go

Podman 5.0 introduces some inspect API type changes: [commit](https://github.com/containers/podman/commit/de845a5b427b82004130f27fec5c27f397722c27), breaking the unmarshal code. Since we don't use the fields, we just delete them. See Issue #331. 
Testing:
- Manully Verified that this works against podman 4.9.3 and 5.0 (nomad 1.7.6). [lightly edited transcript](https://pastebin.com/m8g74y3J)
Note: 
- libpod has just implemented a compatible unmarshal API [here](https://github.com/containers/podman/commit/585af039d7a37580065076648550802d674dd901).

Fix podman 5.0 unmarshall error.

---

.github/workflows/build.yml
.release/linux/postinst
.release/linux/postrm
GNUmakefile

This PR creates .deb and .rpm Linux packages of the nomad-driver-podman
task driver. Given limitations of our packaging system the driver gets
installed in /usr/bin/ but then gets linked to /opt/nomad/plugins/ during
the install steps (and likewise removed during uninstall). This way the
plugin Just Works with the default configuration of Nomad.
Closes https://github.com/hashicorp/nomad-driver-podman/issues/344

build: create linux package during CRT build

---

driver.go
driver_test.go

This PR contains some fixes in the podman driver behaviour when there are multiple sockets in use. Additionally, I've written regression tests that test the behaviour of having multiple sockets.
Fixes:
* If there was one socket with a name different from "default", the attributes would not get prefixed with `driver.podman.attrName` but with `driver.podman.<name of socket>.attrName`. Since this would break existing nomad scheduling, now if a socket is the default socket (`isDefaultClient()` returns true), attributes are written with the `driver.podman.attrName` syntax. Also added `driver.podman.[<name of socket>.]socketName attribute so it's still possible to find the name when it's the default (+ makes it easier if you're using attribute filtering to verify podman has the low-priv socket …

(Regression) Tests and bugfixes for multiple socket implementation

---

CHANGELOG.md
README.md
api/structs.go
config.go
driver.go
driver_test.go

Support --security-opt option as was mention in #297.

config: allow setting `security_opt` option

---

api/container_logs.go

**Problem**: When using the journald logging, empty loglines are added by nomad. (resolves #339 )
**before**:
**after**:

Fix empty log lines in journald (fixes #339)

---

.github/workflows/build.yml

V3 has now been removed and is causing nightly build failures: https://github.com/hashicorp/nomad-driver-podman/actions/runs/13065829235

build: Migrate all use of actions/upload-artifact to v4.

---

driver.go

**Issue:**
When journald is specified as a logging driver, logs should be streamed back to nomad when disable_log_collection is false.
Currently this only works if the task-specific logging configuration is set to journald. If only the global driver configuration is set to log to journald, logs are not streamed back to nomad.
This results in empty task logs in the Nomad UI.
**Fix:**
Updated the logic to use the final resolved logging driver (`createOpts.LogConfiguration.Driver`) instead of the task-specific configuration (`podmanTaskConfig.Logging.Driver`). This ensures:
1. Default logging configurations are honored.
2. Logs are correctly collected and displayed in the Nomad UI.
**Impact:**
- Prevents empty logs in the Nomad UI and ensures consistent log collection.
- Logs are correctly …

Fix: Honor Default Logging Driver Configuration

---

CHANGELOG.md
driver.go

We should always check for nil pointers when accessing response data from the podman client to eliminate the possibly of a panic due to a nil pointer dereference.
Fixes [GH #412](https://github.com/hashicorp/nomad-driver-podman/issues/412)

fingerprint: handle nil pointers in SystemInfo client response

---

api/container_delete.go

Based on the discussion from https://github.com/containers/podman/discussions/25657, the correct parameter for volume is `volumes`.
Using `v`, will not remove the anonymous volumes created.

Fix: use `volumes` instead of `v` for libpod API to delete container

---

README.md
config.go
config_test.go
driver.go

This PR introduces the oom-score-adj configuration option to the current driver implementation. The addition of this option provides users with the ability to adjust the OOM (Out Of Memory) scope for containers managed by Podman, allowing for finer control over resource usage and OOM killer behavior.
Motivation
In scenarios where a resource-heavy application is running within a container, it is often necessary to have more control over how the system’s OOM killer prioritizes processes. The oom-score-adj configuration allows users to fine-tune this behavior, either by preventing the OOM killer from targeting critical processes or by adjusting the OOM score to better suit specific workload requirements.
This feature is particularly useful when:
- Running a resource-intensive application …

Add oom_score_adj config option

---

CHANGELOG.md
api/structs.go
config.go
driver.go
go.mod
go.sum

This PR addresses rebases https://github.com/hashicorp/nomad-driver-podman/pull/359 and addresses review comments. We'd left the PR open for quite some time and don't want to make the original author come back to fix it now, and permissions on the author's fork don't allow me to push to it. I've retained the original commit and authorship of @zandeez, of course. Original PR description below:
---
Resolve https://github.com/hashicorp/nomad-driver-podman/issues/293 and https://github.com/hashicorp/nomad-driver-podman/issues/358 adding ipv6_address, ipv4_address, static_ips and static_mac options for podman tasks.
Podman API version checks whether to set the properties directly or whether to use the new PerNetworkOptions framework.
ipv6_address and ipv4_address are provided for backwards …

Static IP, IPv6 and MAC addresses with Podman >=4.0.0

---

config.go

The `static_mac` field was being validated as though it were a list of strings named `static_macs` instead of a single hardware address supported by the Podman API (and the rest of the configuration code).
Fixes: https://github.com/hashicorp/nomad-driver-podman/issues/450
Ref: https://hashicorp.atlassian.net/browse/NMD-882

fix HCL validation for static_mac field
